version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'devs'
      MYSQL_PASSWORD: 'toni8664'
      MYSQL_ROOT_PASSWORD: 'toni8664'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./.mysql:/var/lib/mysql
      - ./dbs.sql:/dbs/
