version: '3.8'

services:
  mysqldb:
    container_name: MYSQL_DATABASE
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - data:/mysql
    networks:
      - net

networks:
  net:
    external: False

volumes:
  data: