version: '3.8'

services:
  mysqldb:
    container_name: servmysqldb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'toni8664'
    ports:
      - '3306:3306'
    volumes:
      - ./.mysql:/var/lib/mysql

networks:
  default:
    name: mysqldb
